stages:
  - test
  - build
  - docker

test:
  stage: test
  script:
    - echo "Tests OK"
  only:
    - develop

build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn clean package -DskipTests -q
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour
  only:
    - develop

docker:
  stage: docker
  image: docker:24
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker login -u zeynadieng -p $DOCKER_PASSWORD
    - docker build -t zeynadieng/product-api:latest .
    - docker push zeynadieng/product-api:latest
  dependencies:
    - build
  only:
    - develop