# Base image Java 17
FROM openjdk:17-jdk-slim

# Dossier de travail
WORKDIR /app

# Copie le JAR généré
COPY target/product-api-0.0.1-SNAPSHOT.jar app.jar

# Port exposé
EXPOSE 8086

# Lancement
ENTRYPOINT ["java", "-jar", "app.jar"]